# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'
    # We do not set an explicit reviewer, as that is already automatically assigned via CODEOWNERS.
    ignore:
      - dependency-name: 'linked_list_allocator'
        # Ignore buggy version of this dep. Ref: https://github.com/project-oak/oak/pull/3019
        versions: ['0.10.0']
