#!/usr/bin/env bash
#
# Compile protos to TypeScript

rm -rf oak_functions/client/deno/proto
mkdir -p oak_functions/client/deno/proto
deno run --allow-read --allow-write https://deno.land/x/protod@v0.3.7/protod.ts -- gen ./oak_functions/proto/unary_server.proto > ./oak_functions/client/deno/proto/unary_server.ts
