#!/usr/bin/env bash
#
# Compile protos to TypeScript

rm -rf oak_functions/client/deno/proto
mkdir -p oak_functions/client/deno/proto
protoc --proto_path=oak_functions/proto --js_out=import_style=commonjs,binary:oak_functions/client/deno/proto unary_server.proto
deno run --allow-read --allow-write https://deno.land/x/deno_google_protobuf/tools/build.ts oak_functions/client/deno/proto

