[package]
name = "oak_functions_web_client"
version = "0.1.0"
authors = ["Juliette Pretot <hi@juliette.sh>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "rust-crypto"]
rust-crypto = [
  "oak_remote_attestation/rust-crypto",
  "oak_remote_attestation/js"
]

[dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = "*"
console_error_panic_hook = { version = "0.1.6", optional = true }
anyhow = { version = "*", default-features = false }
oak_remote_attestation = { path = "../../remote_attestation/rust/", default-features = false }
oak_remote_attestation_sessions = { path = "../../remote_attestation_sessions/", default-features = false }
oak_functions_abi = { path = "../../oak_functions/abi" }
grpc-web-client = "*"
tonic = { version = "0.6", default-features = false, features = [
  "codegen",
  "prost"
] }
rand = "*"
prost = { version = "0.9", default-features = false }
js-sys = { version = "0.3", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[build-dependencies]
tonic-build = { version = "0.6", default-features = false, features = [
  "prost"
] }

[profile.release]
opt-level = "s"
