name: Build Reproducibility Index

# See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_reproducibility_index:
    runs-on: ubuntu-20.04

    permissions:
      # Allow the job to update the repo with the latest index.
      contents: write
      # Allow the job to add a comment to the PR.
      pull-requests: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Checkout hashes
        uses: actions/checkout@v2
        with:
          ref: hashes
          path: out

      # We need to set up git user details before we can perform git operations.
      - name: Git setup
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Copied from https://github.com/jens-maus/RaspberryMatic/blob/ea6b8ce0dd2d53ea88b2766ba8d7f8e1d667281f/.github/workflows/ci.yml#L34-L40
      - name: free disk space
        run: |
          df --human-readable
          sudo swapoff --all
          sudo rm --force /swapfile
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          df --human-readable

      - name: Docker pull
        timeout-minutes: 10
        run: |
          ./scripts/docker_pull
          df --human-readable

      # Build artifacts that are supposed to be reproducible.
      - name: Build Rust server
        run: |
          sh ./scripts/build_provenance "./scripts/runner build-server" "./oak_loader/bin/oak_loader"
